name: Audit

on:
  workflow_call:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: pip-audit
        run: uv run pip-audit

      - name: Bandit
        run: uv run bandit -r src/ -c pyproject.toml
